jaya_test_web_homepage:
    path:     /
    defaults: { _controller: JayaTestWebBundle:Default:index }

jaya_test_create_item:
    path:     /create
    defaults: { _controller: JayaTestWebBundle:Default:new }

jaya_test_register:
    path:     /register
    defaults: { _controller: JayaTestWebBundle:Security:register }

_security_login:
    pattern:  /login
    defaults: { _controller: JayaTestWebBundle:Security:login }

_security_check:
    pattern:  /login_check

_security_logout:
    pattern:  /logout